### ISSUE TITLE
Exception when I run the example of log4j2 with rabbitmq in docker

### ISSUE THREAD

**Issue by juanwalker** [spring-projects/spring-amqp-samples#17]
Hi, I ran the example of log4j2 it completes well 3 or 4 times the message delivery, but  at the fifth attemp a connection exception is appearing. I'm attaching the stacktrace of the exception, why could be happening this one? I'm using docker to deploy my rabbitmq server.

org.springframework.amqp.AmqpConnectException: java.net.ConnectException: Connection refused: connect
	at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:62) ~[spring-rabbit-1.6.0.RC1.jar:?]
	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:300) ~[spring-rabbit-1.6.0.RC1.jar:?]
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createConnection(CachingConnectionFactory.java:547) ~[spring-rabbit-1.6.0.RC1.jar:?]
	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils$1.createConnection(ConnectionFactoryUtils.java:90) ~[spring-rabbit-1.6.0.RC1.jar:?]
	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.doGetTransactionalResourceHolder(ConnectionFactoryUtils.java:140) ~[spring-rabbit-1.6.0.RC1.jar:?]
	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.getTransactionalResourceHolder(ConnectionFactoryUtils.java:76) ~[spring-rabbit-1.6.0.RC1.jar:?]
	at org.springframework.amqp.rabbit.core.RabbitTemplate.doExecute(RabbitTemplate.java:1345) ~[spring-rabbit-1.6.0.RC1.jar:?]
	at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:1338) ~[spring-rabbit-1.6.0.RC1.jar:?]
	at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:1314) ~[spring-rabbit-1.6.0.RC1.jar:?]
	at org.springframework.amqp.rabbit.core.RabbitAdmin.getQueueProperties(RabbitAdmin.java:335) ~[spring-rabbit-1.6.0.RC1.jar:?]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.redeclareElementsIfNecessary(SimpleMessageListenerContainer.java:1101) [spring-rabbit-1.6.0.RC1.jar:?]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$700(SimpleMessageListenerContainer.java:95) [spring-rabbit-1.6.0.RC1.jar:?]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1277) [spring-rabbit-1.6.0.RC1.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[?:1.8.0_111]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85) ~[?:1.8.0_111]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_111]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_111]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_111]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_111]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_111]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_111]
	at com.rabbitmq.client.impl.FrameHandlerFactory.create(FrameHandlerFactory.java:32) ~[amqp-client-3.6.0.jar:?]
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:676) ~[amqp-client-3.6.0.jar:?]
	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:287) ~[spring-rabbit-1.6.0.RC1.jar:?]
	... 12 more

**Comment by garyrussell** [comment]
I am not familiar with Docker, but this...

>Connection refused: connect

...simply indicates that RabbitMQ is just not running on the server/port you are trying to connect to.

**Comment by juanwalker** [comment]
Hi Gary, thank for reply me. In fact RabbitMQ is runnig and complete 3-4 attemps well but then the exception raises repetead

**Comment by garyrussell** [comment]
It simply can't be running on the configured address/port.

**Comment by juanwalker** [comment]
Here is a more complete log http://pastebin.com/00DGZQYZ, and the content of my log4j2.xml http://pastebin.com/bzH5eSw7 where I only changed localhost by the docker-machine ip

**Comment by artembilan** [comment]
Are you sure that `telnet` can connect to the `192.168.99.100:5672`?

**Comment by artembilan** [comment]
In the beginning of your logs we have:
```
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
```
So, there is no access to your AMQP appended config and, therefore, we see that message in the console. But at the same time we can't connect to the RabbitMQ by some other network reason.

**Comment by juanwalker** [comment]
Thanks guys for your support, artembilan I just rebootr my computer and open again docker and it's working fine now :-), the connection with rabbit in docker is perfect, thank you so much

**Comment by artembilan** [comment]
Great!
Would be glad to know what was the reason of that network glitch, but maybe that is just some Windows specific when we have to reboot after installation such an environment like a Docker...
